name: build

on: 
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-22.04
    #runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Prerequisites
        run: sh ./install.sh 

      - name: add path
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        
      - name: Run test
        run: cargo test
